name: Build (Ubuntu 22.04 + macOS 15)


on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-15]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Linux deps ----------
      - name: Install deps (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build ccache build-essential pkg-config \
            libssl-dev \
            libboost-all-dev \
            libjemalloc-dev \
            libgflags-dev \
            libgoogle-glog-dev \
            libunwind-dev \
            python3-dev curl git

      - name: Build & install Antlr4 C++ runtime 4.13.0 (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          git clone --depth=1 --branch 4.13.0 https://github.com/antlr/antlr4.git /tmp/antlr4
          cmake -S /tmp/antlr4/runtime/Cpp -B /tmp/antlr4/build \
            -DANTLR4_INSTALL=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build /tmp/antlr4/build -j
          sudo cmake --install /tmp/antlr4/build
          # 提示 FindAntlr4：安装到了 /usr/local
          echo "CMAKE_PREFIX_PATH=/usr/local:${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV

      # ---------- macOS deps ----------
      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          # 不装 cmake 以避免 tap 冲突；runner 已预装
          brew install ninja ccache gcc@14 openssl@3 boost gflags glog jemalloc antlr4-cpp-runtime
          echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_SSL_LIB=$(brew --prefix openssl@3)/lib/libssl.dylib" >> $GITHUB_ENV
          echo "OPENSSL_CRYPTO_LIB=$(brew --prefix openssl@3)/lib/libcrypto.dylib" >> $GITHUB_ENV
          echo "OPENSSL_INC=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "BREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
          echo "CC=$(brew --prefix gcc@14)/bin/gcc-14" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix gcc@14)/bin/g++-14" >> $GITHUB_ENV
          echo "$(brew --prefix gcc@14)/bin" >> $GITHUB_PATH

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ccache
            ~/Library/Caches/ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      # ---------- Configure ----------
      - name: Configure (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DOPENSSL_USE_STATIC_LIBS=OFF \
            -DOPENSSL_ROOT_DIR=/usr \
            -DOpenSSL_ssl_LIBRARY=/usr/lib/x86_64-linux-gnu/libssl.so \
            -DOpenSSL_crypto_LIBRARY=/usr/lib/x86_64-linux-gnu/libcrypto.so \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DJemalloc_INCLUDE_DIR=/usr/include \
            -DJemalloc_LIBRARY=/usr/lib/x86_64-linux-gnu/libjemalloc.so

      - name: Configure (macOS with GCC)
        if: runner.os == 'macOS'
        env:
          OPENSSL_ROOT_DIR: ${{ env.OPENSSL_ROOT_DIR }}
          OPENSSL_SSL_LIB: ${{ env.OPENSSL_SSL_LIB }}
          OPENSSL_CRYPTO_LIB: ${{ env.OPENSSL_CRYPTO_LIB }}
          OPENSSL_INC: ${{ env.OPENSSL_INC }}
          BREW_PREFIX: ${{ env.BREW_PREFIX }}
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER="${CC}" \
            -DCMAKE_CXX_COMPILER="${CXX}" \
            -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DOPENSSL_USE_STATIC_LIBS=OFF \
            -DOPENSSL_ROOT_DIR="${OPENSSL_ROOT_DIR}" \
            -DOpenSSL_ssl_LIBRARY="${OPENSSL_SSL_LIB}" \
            -DOpenSSL_crypto_LIBRARY="${OPENSSL_CRYPTO_LIB}" \
            -DOpenSSL_ssl_INCLUDE_DIR="${OPENSSL_INC}" \
            -DOpenSSL_crypto_INCLUDE_DIR="${OPENSSL_INC}" \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DBOOST_ROOT="${BREW_PREFIX}/opt/boost" \
            -DBOOST_INCLUDEDIR="${BREW_PREFIX}/opt/boost/include" \
            -DBOOST_LIBRARYDIR="${BREW_PREFIX}/opt/boost/lib" \
            -DJemalloc_INCLUDE_DIR="${BREW_PREFIX}/opt/jemalloc/include" \
            -DJemalloc_LIBRARY="${BREW_PREFIX}/opt/jemalloc/lib/libjemalloc.dylib" \
            -DCMAKE_PREFIX_PATH="${BREW_PREFIX}/opt/antlr4-cpp-runtime;${CMAKE_PREFIX_PATH}"

      - name: Build
        run: cmake --build build --config Release -j

      - name: Pack artifact
        run: |
          mkdir -p out
          tar -czf out/build-${{ matrix.os }}.tar.gz -C build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: out/build-${{ matrix.os }}.tar.gz
          if-no-files-found: error
          retention-days: 14