name: Build (Ubuntu 22.04 + macOS 15)


on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-15]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build ccache build-essential pkg-config \
            libssl-dev \
            libboost-all-dev \
            python3-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          # 避免 cmake tap 冲突，不再重新安装 cmake
          brew install ninja ccache openssl@3 gcc@14 boost
          echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_SSL_LIB=$(brew --prefix openssl@3)/lib/libssl.dylib" >> $GITHUB_ENV
          echo "OPENSSL_CRYPTO_LIB=$(brew --prefix openssl@3)/lib/libcrypto.dylib" >> $GITHUB_ENV
          echo "OPENSSL_INC=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "BOOST_ROOT=$(brew --prefix boost)" >> $GITHUB_ENV
          echo "BOOST_INCLUDEDIR=$(brew --prefix boost)/include" >> $GITHUB_ENV
          echo "BOOST_LIBRARYDIR=$(brew --prefix boost)/lib" >> $GITHUB_ENV
          echo "CC=$(brew --prefix gcc@14)/bin/gcc-14" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix gcc@14)/bin/g++-14" >> $GITHUB_ENV
          echo "$(brew --prefix gcc@14)/bin" >> $GITHUB_PATH

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ccache
            ~/Library/Caches/ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Configure (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DOPENSSL_USE_STATIC_LIBS=OFF \
            -DOPENSSL_ROOT_DIR=/usr \
            -DOpenSSL_ssl_LIBRARY=/usr/lib/x86_64-linux-gnu/libssl.so \
            -DOpenSSL_crypto_LIBRARY=/usr/lib/x86_64-linux-gnu/libcrypto.so \
            -DBoost_USE_STATIC_LIBS=OFF \
            -DBoost_NO_SYSTEM_PATHS=OFF

      - name: Configure (macOS with GCC)
        if: runner.os == 'macOS'
        env:
          OPENSSL_ROOT_DIR: ${{ env.OPENSSL_ROOT_DIR }}
          OPENSSL_SSL_LIB: ${{ env.OPENSSL_SSL_LIB }}
          OPENSSL_CRYPTO_LIB: ${{ env.OPENSSL_CRYPTO_LIB }}
          OPENSSL_INC: ${{ env.OPENSSL_INC }}
          BOOST_ROOT: ${{ env.BOOST_ROOT }}
          BOOST_INCLUDEDIR: ${{ env.BOOST_INCLUDEDIR }}
          BOOST_LIBRARYDIR: ${{ env.BOOST_LIBRARYDIR }}
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER="${CC}" \
            -DCMAKE_CXX_COMPILER="${CXX}" \
            -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DOPENSSL_USE_STATIC_LIBS=OFF \
            -DOPENSSL_ROOT_DIR="${OPENSSL_ROOT_DIR}" \
            -DOpenSSL_ssl_LIBRARY="${OPENSSL_SSL_LIB}" \
            -DOpenSSL_crypto_LIBRARY="${OPENSSL_CRYPTO_LIB}" \
            -DOpenSSL_ssl_INCLUDE_DIR="${OPENSSL_INC}" \
            -DOpenSSL_crypto_INCLUDE_DIR="${OPENSSL_INC}" \
            -DBoost_USE_STATIC_LIBS=OFF \
            -DBoost_NO_SYSTEM_PATHS=OFF \
            -DBOOST_ROOT="${BOOST_ROOT}" \
            -DBoost_ROOT="${BOOST_ROOT}" \
            -DBOOST_INCLUDEDIR="${BOOST_INCLUDEDIR}" \
            -DBOOST_LIBRARYDIR="${BOOST_LIBRARYDIR}"

      - name: Build
        run: cmake --build build --config Release -j

      - name: Pack artifact
        shell: bash
        run: |
          mkdir -p out
          tar -czf out/build-${{ matrix.os }}.tar.gz -C build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: out/build-${{ matrix.os }}.tar.gz
          if-no-files-found: error
          retention-days: 14